### ISSUE TITLE
Box-Plot Chart / Rampage color by field

### ISSUE THREAD

**Issue by WilliamBelini** [ghtmtt/DataPlotly-docs#4]
Hello! I need help with the box plot graph. It can´t set rampage color (by field) like histogram. The option exists, but don´t work.
Ps. At histogram its don´t work too (have no option), I want say Bar Plot (on Layout space). Yet, Bar Plot details don't work well too, It could have an option to deactivate the label text or put only the total value of cumulated bar (if have a lot of small information, it can't see well)

**Comment by ghtmtt** [comment]
not the correct repository where to raise issues

**Comment by WilliamBelini** [comment]
You have a link to correct repository?

**Comment by ghtmtt** [comment]
https://github.com/ghtmtt/DataPlotly/issues
